# Generated by Django 5.1.1 on 2024-09-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
    ]
